### ISSUE TITLE
不支持网页端购票的场次可以用吗

### ISSUE THREAD

**Issue by jj023721** [kemomi/daimai#6]

**Comment by kemomi** [comment]
其他平台没试过，目前是基于web端的。

**Comment by lblblong** [comment]
看了下代码，不在网页端开售的演唱会买不了，是要基于页面上有抢票按钮的

**Comment by jyk0201** [comment]
这边大麦bp，脚本，代码和猫眼bp可长期提供，有需要的来➕q2814249606，备注github。主打信任不扯皮
